sudo: required
services:
    - docker

berfore_install:
    - docker build -f Dockerfile.prod -t sravanreddyguduru7/docker .

script:
    - docker run sravanreddyguduru7/docker npm run test --code-coverage --watch=false