version: '3'
services: 
    client-app:
        build: 
            dockerfile: Dockerfile.prod
            context: ./
        ports: 
        - "4200:80"
        volumes: 
            - /usr/angular/node_modules
            - .:/usr/angular